/**
 * Auto-generated from NDLA content (CC-BY-SA-4.0)
 * License: Creative Commons Attribution-ShareAlike 4.0 International
 * Attribution: Innhold hentet fra NDLA (Nasjonal digital læringsarena) — ndla.no
 *
 * Sources:
 * - https://ndla.no/article/6454
 *
 * Generated by: scripts/fetch-ndla.js
 * @see schemas/lesson.schema.json
 */
export const lessonsData = {
  "1-1": {
    "title": "Celler og celledeling",
    "subtitle": "Celledeling",
    "goals": [
      "Forstå hva «Vanlig celledeling – mitose» betyr",
      "Forstå hva «Cellas vekstfase» betyr",
      "Forstå hva «Cellas delingsfase» betyr"
    ],
    "dialog": [
      {
        "speaker": "Lærer",
        "text": "I dag skal vi lære om celler og celledeling. Alle levende organismer er bygd opp av celler. Når en organisme vokser, er det fordi cellene vokser og deler seg slik at det blir stadig flere celler. Når encellede organismer vokser, slik som gjær og bakterier, vil de dele seg og bli til to atskilte celler som er helt lik hverandre.",
        "translation": ""
      },
      {
        "speaker": "Elev",
        "text": "Hva betyr «Vanlig celledeling - mitose»?",
        "translation": ""
      },
      {
        "speaker": "Lærer",
        "text": "Når ei celle deler seg, dannes to nye, identiske celler. De to nye cellene skal ha både mitokondrier, ribosomer, cytoplasma og cellekjerne. Vi kaller gjerne den opprinnelig cella for morcelle og de to nye for datterceller. Fordi det er mange mitokondrier og ribosomer i morcellen, fordeles disse mellom dattercellene. Men i morcella er det bare en kjerne og inni den bare ett sett med arvestoff. Før...",
        "translation": ""
      },
      {
        "speaker": "Elev",
        "text": "Hva betyr «Cellas vekstfase»?",
        "translation": ""
      },
      {
        "speaker": "Lærer",
        "text": "Når ei ny celle har oppstått, har den en jobb å gjøre. Først må den vokse opp til normal størrelse. Den starter sitt selvstendige liv med færre mitokondrier og ribosomer så den må produsere flere. Etter hvert som den blir større, må cellemembranen også vokse. Alle stoffene som går med til dette, må cella produsere selv. I tillegg har cella en eller flere oppgaver i kroppen. Hvis det er ei...",
        "translation": ""
      },
      {
        "speaker": "Elev",
        "text": "Hva betyr «Cellas delingsfase»?",
        "translation": ""
      },
      {
        "speaker": "Lærer",
        "text": "Når cella skal dele seg, må arvestoffet kopieres slik at det blir et sett til begge dattercellene som skal oppstå. Etter at kopieringen er ferdig, fordeler de to settene med kromosomer seg i hver sin side av cella, og morcellene avsnøres på midten. Dattercellene går så inn i en ny vekstfase.",
        "translation": ""
      }
    ],
    "checklist": [
      "Jeg kan forklare hva «vanlig celledeling – mitose» betyr",
      "Jeg kan forklare hva «cellas vekstfase» betyr",
      "Jeg kan forklare hva «cellas delingsfase» betyr",
      "Jeg kan oppsummere det viktigste fra leksjonen"
    ],
    "vocabulary": []
  },
  "1-2": {
    "title": "Meiose og arvestoff",
    "subtitle": "Celledeling",
    "goals": [
      "Forstå hva «Produksjon av kjønnsceller – meiose» betyr",
      "Forstå hva «Arvestoffet styrer» betyr"
    ],
    "dialog": [
      {
        "speaker": "Lærer",
        "text": "I dag skal vi lære om meiose og arvestoff. Alle levende organismer er bygd opp av celler. Når en organisme vokser, er det fordi cellene vokser og deler seg slik at det blir stadig flere celler. Når encellede organismer vokser, slik som gjær og bakterier, vil de dele seg og bli til to atskilte celler som er helt lik hverandre.",
        "translation": ""
      },
      {
        "speaker": "Elev",
        "text": "Hva betyr «Produksjon av kjønnsceller - meiose»?",
        "translation": ""
      },
      {
        "speaker": "Lærer",
        "text": "Kjønnsceller, egg- og sædceller, dannes også ved celledeling. Denne celledelingen er forskjellig fra den vanlige celledelingen fordi dattercellene bare skal ha halvparten så mye arvestoff som morcella. I kvinnens eggstokker og mannens testikler finnes spesialiserte morceller som deler seg på denne måten. Morcellene har 46 kromosomer og dattercellene, egg- og sædcellene, har 23 kromosomer. Når det...",
        "translation": ""
      },
      {
        "speaker": "Elev",
        "text": "Hva betyr «Arvestoffet styrer»?",
        "translation": ""
      },
      {
        "speaker": "Lærer",
        "text": "Alt som skjer i cella, styres av oppskriften i arvestoffet. Arvestoffet har mange oppskrifter, og vi kaller dem gener. Et kromosom er en trådformet bit av arvestoff. Et gen er en bit av denne tråden. På et kromosom er det altså mange gener. Når ribosomene i cella skal produsere et protein, hentes oppskriften på proteinet i cellekjernen før produksjonen starter. Selv om arvestoffet er likt i alle...",
        "translation": ""
      }
    ],
    "checklist": [
      "Jeg kan forklare hva «produksjon av kjønnsceller – meiose» betyr",
      "Jeg kan forklare hva «arvestoffet styrer» betyr",
      "Jeg kan oppsummere det viktigste fra leksjonen"
    ],
    "vocabulary": []
  }
};
