/**
 * Auto-generated from NDLA content (CC-BY-SA-4.0)
 * License: Creative Commons Attribution-ShareAlike 4.0 International
 * Attribution: Innhold hentet fra NDLA (Nasjonal digital læringsarena) — ndla.no
 *
 * Sources:
 * - https://ndla.no/article/6454
 *
 * Generated by: scripts/fetch-ndla.js
 * @see schemas/lesson.schema.json
 */
export const exercisesData = {
  "1-1": {
    "exercises": [
      {
        "id": "oppgaveA",
        "type": "writing",
        "title": "Oppgave A: Forklar med egne ord",
        "badges": [
          {
            "text": "Skriving"
          }
        ],
        "description": "Forklar det du har lært om celler og celledeling med egne ord.",
        "template": [
          "Celler og celledeling handler om...",
          "Det viktigste jeg har lært er...",
          "En ting jeg vil lære mer om er..."
        ],
        "placeholder": "Celler og celledeling handler om..."
      }
    ],
    "extraExercises": []
  },
  "1-2": {
    "exercises": [
      {
        "id": "oppgaveA",
        "type": "writing",
        "title": "Oppgave A: Forklar med egne ord",
        "badges": [
          {
            "text": "Skriving"
          }
        ],
        "description": "Forklar det du har lært om meiose og arvestoff med egne ord.",
        "template": [
          "Meiose og arvestoff handler om...",
          "Det viktigste jeg har lært er...",
          "En ting jeg vil lære mer om er..."
        ],
        "placeholder": "Meiose og arvestoff handler om..."
      }
    ],
    "extraExercises": []
  }
};
