/**
 * Auto-generated from NDLA content (CC-BY-SA-4.0)
 * License: Creative Commons Attribution-ShareAlike 4.0 International
 * Attribution: Innhold hentet fra NDLA (Nasjonal digital læringsarena) — ndla.no
 *
 * Sources:
 * - https://ndla.no/article/9806
 * - https://ndla.no/article/38328
 *
 * Generated by: scripts/fetch-ndla.js
 * @see schemas/lesson.schema.json
 */
export const exercisesData = {
  "2-1": {
    "exercises": [
      {
        "id": "oppgaveA",
        "type": "writing",
        "title": "Oppgave A: Forklar med egne ord",
        "badges": [
          {
            "text": "Skriving"
          }
        ],
        "description": "Forklar det du har lært om fotosyntesen med egne ord.",
        "template": [
          "Fotosyntesen handler om...",
          "Det viktigste jeg har lært er...",
          "En ting jeg vil lære mer om er..."
        ],
        "placeholder": "Fotosyntesen handler om..."
      }
    ],
    "extraExercises": []
  },
  "2-2": {
    "exercises": [
      {
        "id": "oppgaveA",
        "type": "matching",
        "title": "Oppgave A: Koble begrep og forklaring",
        "badges": [
          {
            "text": "Begreper"
          }
        ],
        "description": "Koble hvert fagbegrep med riktig forklaring.",
        "isIconGame": false,
        "variableName": "terms-match-2-2",
        "pairs": [
          {
            "id": 1,
            "q": "Energi",
            "a": "er det som får noe til å skje."
          },
          {
            "id": 2,
            "q": "Energikilde",
            "a": "er noe vi kan høste energi fra."
          },
          {
            "id": 3,
            "q": "Stillingsenergi (potensiell energi)",
            "a": "er energi en gjenstand har på grunn av stillingen/posisjo..."
          },
          {
            "id": 4,
            "q": "Bevegelsesenergi (kinetisk energi)",
            "a": "er den energien en gjenstand har på grunn av hastigheten ..."
          },
          {
            "id": 5,
            "q": "Energikjede",
            "a": "er en oversikt over hvordan energi overføres fra en gjens..."
          },
          {
            "id": 6,
            "q": "Energiovergang",
            "a": "er når energi går over fra en form til en annen."
          }
        ]
      },
      {
        "id": "oppgaveB",
        "type": "true-false",
        "title": "Oppgave B: Riktig eller galt?",
        "badges": [],
        "description": "Avgjør om påstandene stemmer med det du har lest.",
        "variableName": "tf-2-2",
        "statements": [
          {
            "q": "Energi er er det som får noe til å skje..",
            "a": true
          },
          {
            "q": "Energikilde er er noe vi kan høste energi fra..",
            "a": true
          },
          {
            "q": "Stillingsenergi (potensiell energi) er er energi en gjenstand har på grunn av stillingen/posisjonen sin..",
            "a": true
          },
          {
            "q": "Energi er det samme som Energiovergang.",
            "a": false
          }
        ]
      },
      {
        "id": "oppgaveC",
        "type": "fill-in",
        "title": "Oppgave C: Fyll inn riktig begrep",
        "badges": [],
        "description": "Fyll inn det manglende fagbegrepet.",
        "items": [
          {
            "pre": "1. er det som får noe til å skje. kalles",
            "answer": "energi",
            "post": ".",
            "width": "w-32"
          },
          {
            "pre": "2. er noe vi kan høste energi fra. kalles",
            "answer": "energikilde",
            "post": ".",
            "width": "w-32"
          },
          {
            "pre": "3. er energi en gjenstand har på grunn av stillingen/posisjonen sin. kalles",
            "answer": "stillingsenergi (potensiell energi)",
            "post": ".",
            "width": "w-32"
          },
          {
            "pre": "4. er den energien en gjenstand har på grunn av hastigheten sin. kalles",
            "answer": "bevegelsesenergi (kinetisk energi)",
            "post": ".",
            "width": "w-32"
          }
        ]
      },
      {
        "id": "oppgaveD",
        "type": "quiz",
        "title": "Oppgave D: Velg riktig svar",
        "badges": [],
        "description": "Velg det riktige alternativet.",
        "questions": [
          {
            "question": "Hva er energi?",
            "options": [
              "er det som får noe til å skje.",
              "er noe vi kan høste energi fra.",
              "er energi en gjenstand har på grunn av stilling...",
              "er den energien en gjenstand har på grunn av ha..."
            ],
            "correctIndex": 0
          },
          {
            "question": "Hva er energikilde?",
            "options": [
              "er noe vi kan høste energi fra.",
              "er det som får noe til å skje.",
              "er energi en gjenstand har på grunn av stilling...",
              "er den energien en gjenstand har på grunn av ha..."
            ],
            "correctIndex": 0
          },
          {
            "question": "Hva er stillingsenergi (potensiell energi)?",
            "options": [
              "er energi en gjenstand har på grunn av stilling...",
              "er det som får noe til å skje.",
              "er noe vi kan høste energi fra.",
              "er den energien en gjenstand har på grunn av ha..."
            ],
            "correctIndex": 0
          }
        ]
      },
      {
        "id": "oppgaveE",
        "type": "interactive-flashcards",
        "title": "Oppgave E: Repetisjonsord",
        "badges": [
          {
            "text": "Begreper"
          }
        ],
        "description": "Øv på de viktigste begrepene med flashkort.",
        "cards": [
          {
            "front": "Energi",
            "back": "er det som får noe til å skje."
          },
          {
            "front": "Energikilde",
            "back": "er noe vi kan høste energi fra."
          },
          {
            "front": "Stillingsenergi (potensiell energi)",
            "back": "er energi en gjenstand har på grunn av stillingen/posisjonen sin."
          },
          {
            "front": "Bevegelsesenergi (kinetisk energi)",
            "back": "er den energien en gjenstand har på grunn av hastigheten sin."
          },
          {
            "front": "Energikjede",
            "back": "er en oversikt over hvordan energi overføres fra en gjenstand til en annen."
          },
          {
            "front": "Energiovergang",
            "back": "er når energi går over fra en form til en annen."
          }
        ]
      },
      {
        "id": "oppgaveF",
        "type": "writing",
        "title": "Oppgave F: Forklar med egne ord",
        "badges": [
          {
            "text": "Skriving"
          }
        ],
        "description": "Forklar det du har lært om hva er energi? med egne ord.",
        "template": [
          "Hva er energi? handler om...",
          "Det viktigste jeg har lært er...",
          "En ting jeg vil lære mer om er..."
        ],
        "placeholder": "Hva er energi? handler om..."
      }
    ],
    "extraExercises": [
      {
        "id": "ekstraovelse-1-2-2",
        "type": "interactive-flashcards",
        "title": "Ekstraøvelse 1: Flere begreper",
        "badges": [
          {
            "type": "strengthening",
            "text": "Styrking"
          },
          {
            "text": "Leksjon 2.2"
          }
        ],
        "description": "Øv på flere begreper fra dette emnet.",
        "cards": [
          {
            "front": "Energi",
            "back": "er det som får noe til å skje."
          },
          {
            "front": "Energikilde",
            "back": "er noe vi kan høste energi fra."
          },
          {
            "front": "Stillingsenergi (potensiell energi)",
            "back": "er energi en gjenstand har på grunn av stillingen/posisjonen sin."
          },
          {
            "front": "Bevegelsesenergi (kinetisk energi)",
            "back": "er den energien en gjenstand har på grunn av hastigheten sin."
          },
          {
            "front": "Energikjede",
            "back": "er en oversikt over hvordan energi overføres fra en gjenstand til en annen."
          },
          {
            "front": "Energiovergang",
            "back": "er når energi går over fra en form til en annen."
          }
        ]
      }
    ]
  }
};
