#!/usr/bin/env node

/**
 * build-demo.js — Assembles a standalone demo from an example course + engine
 *
 * Usage: node scripts/build-demo.js [example-name]
 * Default example: german-a1
 *
 * Output: dist/ directory ready to serve
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// ─── Configuration ───────────────────────────────────────────────────
const exampleName = process.argv[2] || 'german-a1';
const exampleDir = path.join(ROOT, 'examples', exampleName);
const distDir = path.join(ROOT, 'dist');
const engineDir = path.join(ROOT, 'public');
const templatePath = path.join(ROOT, 'public/js/lesson-template/template-international.html');

if (!fs.existsSync(exampleDir)) {
    console.error(`❌ Example "${exampleName}" not found at ${exampleDir}`);
    process.exit(1);
}

// ─── Load example config ─────────────────────────────────────────────
const configPath = path.join(exampleDir, 'papertek.config.js');
const config = (await import(`file://${configPath}`)).default;
const curriculum = config.curricula[0];
const contentLanguage = curriculum.contentPath.split('/').pop(); // "german"
const contentDir = path.join(exampleDir, curriculum.contentPath);

console.log(`🔧 Building demo: ${config.name}`);
console.log(`   Curriculum: ${curriculum.id}`);
console.log(`   Chapters: ${curriculum.chapters}, Lessons/chapter: ${curriculum.lessonsPerChapter}`);

// ─── Clean and create dist ───────────────────────────────────────────
if (fs.existsSync(distDir)) {
    fs.rmSync(distDir, { recursive: true });
}

const dirs = [
    distDir,
    path.join(distDir, 'js'),
    path.join(distDir, 'lessons'),
    path.join(distDir, 'content', contentLanguage),
    path.join(distDir, 'content', contentLanguage, 'exercises-data', curriculum.id),
    path.join(distDir, 'ikoner'),
];
dirs.forEach(d => fs.mkdirSync(d, { recursive: true }));

// ─── 1. Copy engine (JS) ────────────────────────────────────────────
console.log('📦 Copying engine files...');
copyRecursive(path.join(engineDir, 'js'), path.join(distDir, 'js'));

// ─── 2. Copy CSS ────────────────────────────────────────────────────
for (const cssFile of ['papertek.css', 'stylesheet.css']) {
    const src = path.join(engineDir, cssFile);
    if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(distDir, cssFile));
    }
}

// ─── 3. Build monolithic lesson data ─────────────────────────────────
console.log('📝 Building lesson content...');
const allLessons = {};
const chapterTitles = {};

for (let ch = 1; ch <= curriculum.chapters; ch++) {
    const chapterFile = path.join(contentDir, 'lessons-data', `chapter-${ch}.js`);
    if (!fs.existsSync(chapterFile)) {
        console.warn(`   ⚠️ Missing ${chapterFile}`);
        continue;
    }

    const mod = await import(`file://${chapterFile}`);
    const raw = mod.lessonsData;

    // Build chapter title from first lesson
    const firstLessonId = `${ch}-1`;
    if (raw[firstLessonId]) {
        chapterTitles[ch] = `Chapter ${ch}`;
    }

    // Normalize each lesson
    for (const [lessonId, lesson] of Object.entries(raw)) {
        allLessons[lessonId] = normalizeLessonData(lesson);
    }
}

const lessonsFileContent = `// Auto-generated by build-demo.js
export const chapterTitles = ${JSON.stringify(chapterTitles, null, 2)};

export const lessonsData = ${JSON.stringify(allLessons, null, 2)};
`;

const contentSuffix = curriculum.id;
fs.writeFileSync(
    path.join(distDir, 'content', contentLanguage, `lessons-data-${contentSuffix}.js`),
    lessonsFileContent
);

// ─── 4. Build monolithic grammar data ────────────────────────────────
console.log('📝 Building grammar content...');
const allGrammar = {};

for (let ch = 1; ch <= curriculum.chapters; ch++) {
    const grammarFile = path.join(contentDir, 'grammar-data', `chapter-${ch}.js`);
    if (!fs.existsSync(grammarFile)) continue;

    const mod = await import(`file://${grammarFile}`);
    const raw = mod.grammarModules;

    // Expand chapter-keyed to lesson-keyed
    for (const [chapterKey, modules] of Object.entries(raw)) {
        for (let lesson = 1; lesson <= curriculum.lessonsPerChapter; lesson++) {
            const lessonId = `${chapterKey}-${lesson}`;
            // Only assign if lesson exists in lesson data
            if (allLessons[lessonId]) {
                allGrammar[lessonId] = modules;
            }
        }
    }
}

const grammarFileContent = `// Auto-generated by build-demo.js
export const grammarData = ${JSON.stringify(allGrammar, null, 2)};
`;

fs.writeFileSync(
    path.join(distDir, 'content', contentLanguage, `grammar-data-${contentSuffix}.js`),
    grammarFileContent
);

// ─── 5. Copy exercise files as-is (already per-chapter) ─────────────
console.log('📝 Copying exercise files...');
const exerciseSrcDir = path.join(contentDir, 'exercises-data', curriculum.id);
const exerciseDestDir = path.join(distDir, 'content', contentLanguage, 'exercises-data', curriculum.id);

if (fs.existsSync(exerciseSrcDir)) {
    copyRecursive(exerciseSrcDir, exerciseDestDir);
}

// ─── 6. Create stub files for missing content ────────────────────────
console.log('📝 Creating stub content files...');

const stubs = {
    [`pronunciation-data-${contentSuffix}.js`]: 'export const pronunciationData = {};',
    [`culture-data-${contentSuffix}.js`]: 'export const cultureData = {};',
    'vocabulary-data.js': 'export const vocabularyData = {};',
    'characters-data.js': `export function getCharacterName(name) { return name; }`,
};

for (const [filename, content] of Object.entries(stubs)) {
    fs.writeFileSync(
        path.join(distDir, 'content', contentLanguage, filename),
        `// Auto-generated stub by build-demo.js\n${content}\n`
    );
}

// ─── 7. Generate lesson HTML files ───────────────────────────────────
console.log('📄 Generating lesson pages...');
const template = fs.readFileSync(templatePath, 'utf-8');

// Fix template paths for demo structure: lessons are in lessons/ subfolder
// Template expects ../js/main.js (from lessons/ → dist root → js/)
// Template expects ../papertek.css (from lessons/ → dist root)
// These are already correct for our structure

for (const [lessonId, lessonData] of Object.entries(allLessons)) {
    const [chapter, lesson] = lessonId.split('-');
    const fileName = `${curriculum.filePrefix}-${chapter}-${lesson}.html`;
    const title = lessonData.dialog?.title || lessonData._originalTitle || `Lesson ${chapter}.${lesson}`;
    const lessonNumber = `${chapter}.${lesson}`;

    // Check if this lesson has extra exercises
    const hasExtras = await checkHasExtraExercises(chapter, curriculum);

    let html = template
        .replace(/\{\{LESSON_NUMBER\}\}/g, lessonNumber)
        .replace(/\{\{TITLE\}\}/g, escapeHtml(title))
        .replace(/\{\{CHAPTER_ID\}\}/g, lessonId)
        .replace(/\{\{FILE_NAME\}\}/g, fileName)
        .replace(/\{\{LESSON_DOT_NUMBER\}\}/g, lessonNumber);

    // Handle extra exercises tab
    if (hasExtras) {
        html = html.replace('{{EKSTRAOVELSER_TAB}}', generateExtraExercisesTab());
    } else {
        html = html.replace('{{EKSTRAOVELSER_TAB}}', '');
    }

    // Fix content path for demo structure
    // The content-loader resolves paths relative to the JS file location
    // We need the international page detection to work, which it will via data-ui-language="en"

    // Fix start button text
    html = html.replace('{{START_BUTTON_TEXT}}', 'Start');

    // Fix service worker path
    html = html.replace("'./sw-international.js'", "'../sw-international.js'");
    html = html.replace("{ scope: '/international/' }", "{ scope: '/' }");

    // Fix manifest path
    html = html.replace('href="./manifest.json"', 'href="../manifest.json"');

    fs.writeFileSync(path.join(distDir, 'lessons', fileName), html);
    console.log(`   ✅ ${fileName}`);
}

// ─── 8. Generate homepage ────────────────────────────────────────────
console.log('🏠 Generating homepage...');
generateHomepage(config, curriculum, allLessons, chapterTitles);

// ─── 9. Generate manifest.json ───────────────────────────────────────
const manifest = {
    name: config.name,
    short_name: curriculum.id,
    start_url: '.',
    display: 'standalone',
    background_color: '#f8fafc',
    theme_color: '#2563eb',
    icons: []
};
fs.writeFileSync(path.join(distDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

// ─── 10. Generate minimal service worker ─────────────────────────────
fs.writeFileSync(path.join(distDir, 'sw-international.js'), `// Minimal service worker for demo
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()));
`);

console.log('\n✅ Demo built successfully!');
console.log(`   Output: ${distDir}/`);
console.log(`   Lessons: ${Object.keys(allLessons).length}`);
console.log(`\n   Run: npx http-server dist -p 8080`);

// ═════════════════════════════════════════════════════════════════════
// Helper Functions
// ═════════════════════════════════════════════════════════════════════

/**
 * Normalize example lesson data to engine format
 * - goals → learningGoals
 * - flat dialog[] → structured { title, lines: [{ person, text }] }
 */
function normalizeLessonData(lesson) {
    const normalized = {};

    // goals → learningGoals
    normalized.learningGoals = lesson.learningGoals || lesson.goals || [];

    // Normalize dialog format
    if (Array.isArray(lesson.dialog)) {
        // Flat array format → structured
        const firstLine = lesson.dialog[0];
        normalized.dialog = {
            title: lesson.title || '',
            description: lesson.subtitle || '',
            lines: lesson.dialog.map(line => ({
                person: line.speaker || line.person,
                text: line.text,
                translation: line.translation
            }))
        };
    } else if (lesson.dialog) {
        // Already structured
        normalized.dialog = lesson.dialog;
    }

    // Pass through other fields
    normalized.checklist = lesson.checklist || [];
    normalized.vocabulary = lesson.vocabulary;
    normalized.additionalTexts = lesson.additionalTexts;
    normalized.phraseTables = lesson.phraseTables;
    normalized.factCards = lesson.factCards;

    // Store original title for template generation
    normalized._originalTitle = lesson.title;

    return normalized;
}

/**
 * Check if a chapter has extra exercises
 */
async function checkHasExtraExercises(chapter, curriculum) {
    try {
        const exerciseFile = path.join(contentDir, 'exercises-data', curriculum.id, `chapter-${chapter}.js`);
        if (!fs.existsSync(exerciseFile)) return false;
        const mod = await import(`file://${exerciseFile}`);
        for (const data of Object.values(mod.exercisesData)) {
            if (data.extraExercises && data.extraExercises.length > 0) return true;
        }
    } catch { /* ignore */ }
    return false;
}

/**
 * Generate the extra exercises tab HTML
 */
function generateExtraExercisesTab() {
    return `
            <div class="tab-content hidden space-y-8" id="extra-exercises">
                <div id="extra-exercises-content">
                    <!-- Extra exercises loaded dynamically -->
                </div>
                <div class="mt-12 p-6 bg-neutral-100/60 rounded-lg text-center">
                    <button
                        class="next-tab-btn bg-primary-500 text-white font-bold py-3 px-5 rounded-lg hover:bg-primary-600 transition-colors"
                        data-next-tab="dialog" data-i18n="btn_next">
                        Next
                    </button>
                </div>
            </div>`;
}

/**
 * Generate the demo homepage
 */
function generateHomepage(config, curriculum, lessons, chapterTitles) {
    const lessonEntries = Object.entries(lessons);

    // Group by chapter
    const chapters = {};
    for (const [lessonId, data] of lessonEntries) {
        const [ch] = lessonId.split('-');
        if (!chapters[ch]) chapters[ch] = [];
        const fileName = `${curriculum.filePrefix}-${lessonId.replace('-', '-')}.html`;
        chapters[ch].push({
            id: lessonId,
            title: data._originalTitle || data.dialog?.title || `Lesson ${lessonId}`,
            fileName,
            goals: data.learningGoals || []
        });
    }

    const chaptersHtml = Object.entries(chapters).map(([ch, chapterLessons]) => {
        const lessonsHtml = chapterLessons.map(l => `
                    <a href="lessons/${l.fileName}" class="block p-4 bg-surface rounded-lg shadow-sm hover:shadow-md transition-shadow border border-neutral-200 hover:border-primary-300">
                        <h3 class="text-lg font-bold text-primary-700">${escapeHtml(l.title)}</h3>
                        <p class="text-sm text-neutral-500 mt-1">Lesson ${l.id}</p>
                        ${l.goals.length > 0 ? `<ul class="mt-2 text-sm text-neutral-600 list-disc list-inside">${l.goals.slice(0, 2).map(g => `<li>${escapeHtml(g)}</li>`).join('')}</ul>` : ''}
                    </a>`).join('\n');

        return `
                <div class="mb-10">
                    <h2 class="text-2xl font-bold text-primary-800 mb-4">Chapter ${ch}: ${chapterTitles[ch] || ''}</h2>
                    <div class="grid sm:grid-cols-2 gap-4">
                        ${lessonsHtml}
                    </div>
                </div>`;
    }).join('\n');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>${escapeHtml(config.name)} — Demo</title>
    <link href="papertek.css" rel="stylesheet" />
    <link href="stylesheet.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
</head>
<body class="bg-neutral-50 text-neutral-800">
    <div class="container mx-auto p-4 sm:p-6 md:p-8 max-w-4xl">
        <header class="text-center mb-12">
            <div class="inline-block bg-primary-100 text-primary-700 text-sm font-medium px-3 py-1 rounded-full mb-4">
                Papertek Demo
            </div>
            <h1 class="text-4xl md:text-5xl font-bold text-primary-700 tracking-tight">
                ${escapeHtml(config.name)}
            </h1>
            <p class="mt-3 text-lg text-neutral-600 max-w-2xl mx-auto">
                ${escapeHtml(config.description)}
            </p>
            <div class="mt-4 flex justify-center gap-4 text-sm text-neutral-500">
                <span>${curriculum.chapters} chapters</span>
                <span>·</span>
                <span>${Object.keys(lessons).length} lessons</span>
                <span>·</span>
                ${curriculum.cefrLevel ? `<span>CEFR ${curriculum.cefrLevel}</span>` : ''}
            </div>
        </header>

        <main>
            ${chaptersHtml}
        </main>

        <footer class="mt-16 pt-8 border-t border-neutral-200 text-center text-sm text-neutral-500">
            <p>Built with <a href="https://github.com/Papertek-forlag-AS/edu-framework" class="text-primary-600 hover:underline">Papertek — Framework for Education</a></p>
        </footer>
    </div>
</body>
</html>`;

    fs.writeFileSync(path.join(distDir, 'index.html'), html);
}

/**
 * Recursively copy a directory
 */
function copyRecursive(src, dest) {
    if (!fs.existsSync(src)) return;

    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }

    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);

        if (entry.isDirectory()) {
            copyRecursive(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

/**
 * Escape HTML special characters
 */
function escapeHtml(str) {
    if (!str) return '';
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
