#!/usr/bin/env node
/**
 * NDLA Content Pipeline
 *
 * Fetches educational content from NDLA's public API and transforms it
 * into Papertek content files (lessons, exercises, theory modules).
 *
 * Usage:
 *   node scripts/fetch-ndla.js [--config <path>] [--output <path>]
 *
 * Defaults:
 *   --config  scripts/ndla/naturfag-vg1-articles.json
 *   --output  examples/naturfag-vg1
 *
 * @license CC-BY-SA-4.0 (generated content inherits NDLA's license)
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchArticle } from './ndla/api-client.js';
import { parseArticle, transformToLesson, generateTheoryModules } from './ndla/transform-article.js';
import { generateExercises } from './ndla/generate-exercises.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// ── Parse CLI args ──────────────────────────────────────────────────
function parseArgs() {
  const args = process.argv.slice(2);
  const result = {
    config: join(__dirname, 'ndla/naturfag-vg1-articles.json'),
    output: join(ROOT, 'examples/naturfag-vg1'),
  };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--config' && args[i + 1]) result.config = args[++i];
    if (args[i] === '--output' && args[i + 1]) result.output = args[++i];
  }
  return result;
}

// ── Attribution header for generated files ──────────────────────────
function attribution(articleIds) {
  const sources = articleIds.map(id => ` * - https://ndla.no/article/${id}`).join('\n');
  return `/**
 * Auto-generated from NDLA content (CC-BY-SA-4.0)
 * License: Creative Commons Attribution-ShareAlike 4.0 International
 * Attribution: Innhold hentet fra NDLA (Nasjonal digital læringsarena) — ndla.no
 *
 * Sources:
${sources}
 *
 * Generated by: scripts/fetch-ndla.js
 * @see schemas/lesson.schema.json
 */`;
}

// ── Write a JS module file ──────────────────────────────────────────
async function writeModule(filePath, header, exportName, data) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });

  const content = `${header}\nexport const ${exportName} = ${JSON.stringify(data, null, 2)};\n`;
  await writeFile(filePath, content);
  console.log(`  ✓ ${filePath.replace(ROOT + '/', '')}`);
}

// ── Main pipeline ───────────────────────────────────────────────────
async function main() {
  const { config: configPath, output: outputDir } = parseArgs();

  console.log('╔══════════════════════════════════════════════╗');
  console.log('║  NDLA → Papertek Content Pipeline            ║');
  console.log('╚══════════════════════════════════════════════╝\n');

  // 1. Read article mapping config
  const configRaw = await readFile(configPath, 'utf-8');
  const config = JSON.parse(configRaw);
  console.log(`Subject: ${config.subject}`);
  console.log(`Chapters: ${config.chapters.length}\n`);

  // 2. Fetch all unique articles
  const articleIds = [...new Set(
    config.chapters.flatMap(ch => ch.lessons.map(l => l.articleId))
  )];
  console.log(`Fetching ${articleIds.length} article(s) from NDLA API...`);

  const articles = {};
  for (const id of articleIds) {
    articles[id] = await fetchArticle(id);
  }
  console.log('');

  // 3. Parse all articles
  const parsed = {};
  for (const [id, article] of Object.entries(articles)) {
    parsed[id] = parseArticle(article);
    const termCount = parsed[id].terms.length;
    const sectionCount = parsed[id].sections.length;
    console.log(`  Parsed article ${id}: ${sectionCount} sections, ${termCount} terms`);
  }
  console.log('');

  // Determine content subdirectory from config
  const curricId = config.chapters[0]?.lessons?.[0]?.articleId
    ? config.subject.toLowerCase().replace(/\s+vg\d+/i, '').replace(/\s+/g, '-')
    : 'content';
  const contentDir = join(outputDir, 'content', curricId.replace('naturfag', 'naturfag'));

  // 4. Generate lesson data per chapter
  console.log('Generating content files...');
  for (const chapter of config.chapters) {
    const chapterNum = chapter.chapter;
    const lessonsData = {};
    const exercisesData = {};
    const grammarModules = {};

    const chapterArticleIds = [...new Set(chapter.lessons.map(l => l.articleId))];

    for (const lesson of chapter.lessons) {
      const lessonId = `${chapterNum}-${lesson.lesson}`;
      const articleParsed = parsed[lesson.articleId];

      if (!articleParsed) {
        console.warn(`  ⚠ Article ${lesson.articleId} not found, skipping lesson ${lessonId}`);
        continue;
      }

      // Transform to lesson data
      lessonsData[lessonId] = transformToLesson(articleParsed, lesson);

      // Generate exercises
      const { exercises, extraExercises } = generateExercises(articleParsed, lesson, lessonId);
      exercisesData[lessonId] = { exercises, extraExercises };

      // Generate theory modules (keyed by chapter for grammar-data)
      const theory = generateTheoryModules(articleParsed, lesson);
      grammarModules[String(chapterNum)] = [
        ...(grammarModules[String(chapterNum)] || []),
        ...theory,
      ];
    }

    // Write lesson data
    const header = attribution(chapterArticleIds);
    await writeModule(
      join(contentDir, 'lessons-data', `chapter-${chapterNum}.js`),
      header, 'lessonsData', lessonsData
    );

    // Write exercises data
    // Determine curriculum folder name from config
    const curricFolderName = config.subject.toLowerCase().replace(/\s+/g, '-');
    await writeModule(
      join(contentDir, 'exercises-data', curricFolderName, `chapter-${chapterNum}.js`),
      header, 'exercisesData', exercisesData
    );

    // Write grammar/theory modules
    await writeModule(
      join(contentDir, 'grammar-data', `chapter-${chapterNum}.js`),
      header, 'grammarModules', grammarModules
    );
  }

  console.log('\n✅ Done! Content files written to:');
  console.log(`   ${outputDir.replace(ROOT + '/', '')}/`);
  console.log(`\nNext steps:`);
  console.log(`   node scripts/build-demo.js naturfag-vg1`);
}

main().catch(err => {
  console.error('❌ Pipeline error:', err.message);
  process.exit(1);
});
