/**
 * Auto-generated from NDLA content (CC-BY-SA-4.0)
 * License: Creative Commons Attribution-ShareAlike 4.0 International
 * Attribution: Innhold hentet fra NDLA (Nasjonal digital læringsarena) — ndla.no
 *
 * Sources:
 * - https://ndla.no/article/9806
 * - https://ndla.no/article/38328
 *
 * Generated by: scripts/fetch-ndla.js
 * @see schemas/lesson.schema.json
 */
export const grammarModules = {
  "2": [
    {
      "type": "heading",
      "level": 3,
      "text": "Fotosyntesen"
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Mulig med liv på land"
    },
    {
      "type": "explanation",
      "text": "Da plantene hadde inntatt landjorda, var det mulig for noen dyr å krabbe opp på land. Dette gjorde de først for å unngå rovdyra i havet, men etter hvert utviklet de seg til å kunne tilbringe lengre tid på land enn i vann. De utviklet lunger for å kunne ta opp oksygen fra lufta i stedet for fra vannet. Plantene og fotosyntesen er derfor opphavet til nesten alt liv som eksisterer på planeten vår."
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Produserer sukker"
    },
    {
      "type": "explanation",
      "text": "Når planten driver fotosyntese, produserer den sukker. Dette sukkeret blir brukt til mye forskjellig. Planten bruker sukker til næring, som den for eksempel lagrer i knoller under bakken. Da omdannes sukkeret til stivelse – dette skjer blant annet i poteten. Planten bruker også sukkeret til å danne byggematerialer for å vokse. Da omdannes sukkeret til cellulose – som for eksempel stammen på et tre. I tillegg til at sukkeret er næring og byggemateriale for planten, er det også næring for dyr og mennesker. Det er bare planter og alger som driver fotosyntese og kan produsere sukker. Vi kaller dem derfor produsenter."
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Klorofyllkorn eller grønnkorn"
    },
    {
      "type": "explanation",
      "text": "For at plantene skal kunne drive med fotosyntese, har de grønne korn inne i cellene. Grønnkorna har klorofyll som kan fange energien i sollyset. De fungerer nesten som solcellepaneler. Energien som plantene henter fra sollyset, bruker de til å danne sukker: glukose. Oksygen er et avfallsprodukt som plantene slipper ut. I tillegg til fotosyntesen må planter drive med celleånding. Det gjør de hele tida. Er det nok lys, blir det produsert mer energi i fotosyntesen enn det blir brukt i celleåndinga, men er det mindre lys, vil plantene etter hvert ikke klare å hente energi gjennom fotosyntesen, og de må gå over på rein celleånding. Når plantene bruker like mye oksygen i celleåndinga som de slipper ut gjennom fotosyntesen, kaller vi det plantenes kompensasjonsnivå. Ulike planter har ulikt kompensasjonsnivå, avhengig av om de er tilpasset å vokse i mye eller lite lys."
    },
    {
      "type": "info-box",
      "boxType": "remember",
      "title": "Husk!",
      "content": "Da plantene hadde inntatt landjorda, var det mulig for noen dyr å krabbe opp på land. Dette gjorde de først for å unngå rovdyra i havet, men etter hvert utviklet de seg til å kunne tilbringe lengre tid på land enn i vann. De utviklet lunger for å kunne ta opp oksygen fra lufta i stedet for fra vannet. Når planten driver fotosyntese, produserer den sukker. Dette sukkeret blir brukt til mye forskjellig. Planten bruker sukker til næring, som den for eksempel lagrer i knoller under bakken. Da omdannes sukkeret til stivelse – dette skjer blant annet i poteten. For at plantene skal kunne drive med fotosyntese, har de grønne korn inne i cellene. Grønnkorna har klorofyll som kan fange energien i sollyset. De fungerer nesten som solcellepaneler. Energien som plantene henter fra sollyset, bruker de til å danne sukker: glukose. Oksygen er et avfallsprodukt som plantene slipper ut."
    },
    {
      "type": "heading",
      "level": 3,
      "text": "Hva er energi?"
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Energi får noe til å skje"
    },
    {
      "type": "explanation",
      "text": "Energi er det som får noe til å skje: Når du skrur på telefonen, vil energi fra batteriet gjøre at du kan sende meldinger med den. Når du slår på lyset, gir elektrisk energi lys og varme, og energien i maten du spiser, gir deg energi til alt du gjør i løpet av en dag."
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Energikilder"
    },
    {
      "type": "explanation",
      "text": "Det vi kan høste energi fra, kaller vi energikilder. Med energikilde mener vi energi som finnes naturlig, som sol-, vind- og vannenergi, oljelagre under havbunnen og kjerneenergi."
    },
    {
      "type": "heading",
      "level": 4,
      "text": "Energi er konstant"
    },
    {
      "type": "explanation",
      "text": "Energi kan ikke oppstå eller forsvinne, den kan bare gå over i andre former. Det betyr at den totale mengden energi er den samme hele tida. Dette høres litt rart ut, vi har jo alle opplevd at vi ikke har strøm på telefonen, og det virker dermed som om den elektriske energien har forsvunnet. Det har den ikke! Den har rett og slett gått over til andre former for energi: varmeenergi og lysenergi."
    },
    {
      "type": "rule-table",
      "headers": [
        "Begrep",
        "Forklaring"
      ],
      "rows": [
        [
          "Energi",
          "er det som får noe til å skje."
        ],
        [
          "Energikilde",
          "er noe vi kan høste energi fra."
        ],
        [
          "Stillingsenergi (potensiell energi)",
          "er energi en gjenstand har på grunn av stillingen/posisjonen sin."
        ],
        [
          "Bevegelsesenergi (kinetisk energi)",
          "er den energien en gjenstand har på grunn av hastigheten sin."
        ],
        [
          "Energikjede",
          "er en oversikt over hvordan energi overføres fra en gjenstand til en annen."
        ],
        [
          "Energiovergang",
          "er når energi går over fra en form til en annen."
        ]
      ]
    },
    {
      "type": "info-box",
      "boxType": "remember",
      "title": "Husk!",
      "content": "Energi er det som får noe til å skje: Når du skrur på telefonen, vil energi fra batteriet gjøre at du kan sende meldinger med den. Når du slår på lyset, gir elektrisk energi lys og varme, og energien i maten du spiser, gir deg energi til alt du gjør i løpet av en dag. Det vi kan høste energi fra, kaller vi energikilder. Med energikilde mener vi energi som finnes naturlig, som sol-, vind- og vannenergi, oljelagre under havbunnen og kjerneenergi. Energi kan ikke oppstå eller forsvinne, den kan bare gå over i andre former. Det betyr at den totale mengden energi er den samme hele tida. Dette høres litt rart ut, vi har jo alle opplevd at vi ikke har strøm på telefonen, og det virker dermed som om den elektriske energien har forsvunnet. Det har den ikke! Den har rett og slett gått over til andre former for energi: varmeenergi og lysenergi."
    }
  ]
};
